# Generated by Django 5.2.7 on 2025-10-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('deporte', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('fundado_en', models.IntegerField()),
            ],
        ),
    ]
