# Generated by Django 5.2.7 on 2025-10-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='deporte',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fundado_en',
        ),
        migrations.AddField(
            model_name='equipo',
            name='anio_fundacion',
            field=models.PositiveIntegerField(blank=True, help_text='Año de fundación del club', null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='apodo',
            field=models.CharField(blank=True, help_text='Apodo del club, los hinchas y su estadio', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='cantidad_copas',
            field=models.CharField(blank=True, help_text='Cantidad de copas, títulos, veces que ganó el torneo, etc', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='cantidad_hinchas',
            field=models.CharField(blank=True, help_text='Cantidad de hinchas aproximadamente (puede no ser exacta)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='clasico_rival',
            field=models.CharField(blank=True, help_text='Clásico rival y cuántos partidos le lleva', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(blank=True, help_text='Foto del escudo del club', null=True, upload_to='escudos/'),
        ),
    ]
