# Generated by Django 5.2.7 on 2025-10-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeportes', '0002_remove_equipo_ciudad_remove_equipo_deporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad principal del club', max_length=100, null=True),
        ),
    ]
