# Generated by Django 5.2.7 on 2025-10-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeportes', '0003_equipo_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estadio',
            field=models.ImageField(blank=True, help_text='Foto del estadio del club', null=True, upload_to='estadios/'),
        ),
    ]
