# Generated by Django 5.2.7 on 2025-11-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeportes', '0004_equipo_estadio'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='mapa',
            field=models.TextField(blank=True, help_text='Código embed del mapa de Google Maps del estadio', null=True),
        ),
    ]
