# Generated by Django 5.2.7 on 2025-11-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeportes', '0005_equipo_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ubicacion_estadio',
            field=models.CharField(blank=True, help_text='Ubicación del estadio (dirección)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='mapa',
            field=models.TextField(blank=True, help_text='Código embed del mapa de Google Maps (iframe)', null=True),
        ),
    ]
