# Generated by Django 5.2.7 on 2025-11-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeportes', '0006_equipo_ubicacion_estadio_alter_equipo_mapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombre_estadio',
            field=models.CharField(blank=True, help_text='Nombre del estadio del club', max_length=200, null=True),
        ),
    ]
