# Generated by Django 5.2.7 on 2025-11-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeportes', '0008_equipo_marcador_rival_alter_equipo_clasico_rival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='marcador_rival',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasico_rival',
            field=models.CharField(blank=True, help_text='Clásico rival y cuántos partidos le lleva', max_length=100, null=True),
        ),
    ]
