# Generated by Django 5.2.7 on 2025-11-08 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeportes', '0009_remove_equipo_marcador_rival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='marcador_rival',
            field=models.CharField(blank=True, help_text='Cuántos partidos le lleva el equipo al rival', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasico_rival',
            field=models.CharField(max_length=100, blank=True, null=True, help_text='Clásico rival y cuántos partidos le lleva'
        ),
        ),
    ]
