# Generated by Django 5.2.7 on 2025-11-18 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeportes', '0010_equipo_marcador_rival_alter_equipo_clasico_rival'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='marcador_rival',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasico_rival',
            field=models.CharField(blank=True, help_text='Clásico rival y cuántos partidos le lleva', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PartidoAmistoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_vos', models.IntegerField()),
                ('goles_pc', models.IntegerField()),
                ('resultado', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('equipo_pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_pc', to='appdeportes.equipo')),
                ('equipo_vos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_vos', to='appdeportes.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
