# Generated by Django 5.2.7 on 2025-11-19 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeportes', '0011_remove_equipo_marcador_rival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidoamistoso',
            name='equipo_pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_pc', to='appdeportes.equipo'),
        ),
        migrations.AlterField(
            model_name='partidoamistoso',
            name='equipo_vos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_vos', to='appdeportes.equipo'),
        ),
    ]
